<a href="https://colab.research.google.com/github/hamzzihyun/coachingstudy-9_AI_basic/blob/main/Week2_mission_jihyun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# Q1
# test score, mid : 50, final : 75

class Score():
    # TODO
    def __init__(self, mid, final): # 초기생성자
      # (1) __변수명 : 생성자의 인스턴스를 private로 선언
      self.__mid = mid  # pirvate 선언
      self.__final = final

    @property  # private된 변수 반환
    def mid(self):  # (2) 데코레이터를 이용해 데이터 저장
      return self.__mid

    @property
    def final(self):
      return self.__final

if __name__ == "__main__":
  # 출력함수
  score = Score (50, 75)  # Score 클래스에 속하는 인스턴스로 score 객체 생성
  print((score.mid + score.final) / 2)

62.5


In [9]:
# 02

class Car():

    def __init__(self, fuel, wheels) :
        self.fuel = fuel
        self.wheels = wheels

class Bike(Car): # Car 클래스 상속
    def __init__(self, fuel, wheels, size): # size인자 추가
        super().__init__(fuel, wheels) # 부모객체인 Car 클래스 속성을 상속
        self.size = size # 자식클래스 Bike에서 추가된 속성

bike = Bike('gas', 2, 'small')

print(bike.fuel, bike.wheels, bike.size)

gas 2 small


### 📑 **Upload file for question 3,4,5**

In [28]:
from google.colab import files
uploaded = files.upload()

Saving data-01-test-score.csv to data-01-test-score (1).csv


In [85]:
# Q3
# 파일의 경로를 f1le_path로 설정
# ex) file_path = "./data-01-test-score.csv"

import csv
import numpy as np

file_path = "data-01-test-score.csv"

def read_file(file_path):
    # TODO
    csv_list = []
    with open(file_path, 'r') as csv_file:
      reader = csv.reader(csv_file)
      csv_list = list(reader)
      return np.array(csv_list)

print(read_file(file_path))

[['73' '80' '75' '152']
 ['93' '88' '93' '185']
 ['89' '91' '90' '180']
 ['96' '98' '100' '196']
 ['73' '66' '70' '142']
 ['53' '46' '55' '101']
 ['69' '74' '77' '149']
 ['47' '56' '60' '115']
 ['87' '79' '90' '175']
 ['79' '70' '88' '164']
 ['69' '70' '73' '141']
 ['70' '65' '74' '141']
 ['93' '95' '91' '184']
 ['79' '80' '73' '152']
 ['70' '73' '78' '148']
 ['93' '89' '96' '192']
 ['78' '75' '68' '147']
 ['81' '90' '93' '183']
 ['88' '92' '86' '177']
 ['78' '83' '77' '159']
 ['82' '86' '90' '177']
 ['86' '82' '89' '175']
 ['78' '83' '85' '175']
 ['76' '83' '71' '149']
 ['96' '93' '95' '192']]


In [98]:
# Q4

file_path = "data-01-test-score.csv"

class ReadCSV():
    def __init__(self, file_path) :
       # TODO
        self.file_path = file_path

    def read_file(self):
        # TODO
        with open(self.file_path, 'r') as f:
          data = list(csv.reader(f))
          for idx in range(len(data)):
            data[idx] = [int(i) for i in data[idx]]
        self.data = data
        return np.array(self.data)

    def merge_list(self):
        # TODO
        return [sum(i) for i in self.data]

read_csv = ReadCSV(file_path)
print(read_csv.read_file())
print()
print(read_csv.merge_list())

[[ 73  80  75 152]
 [ 93  88  93 185]
 [ 89  91  90 180]
 [ 96  98 100 196]
 [ 73  66  70 142]
 [ 53  46  55 101]
 [ 69  74  77 149]
 [ 47  56  60 115]
 [ 87  79  90 175]
 [ 79  70  88 164]
 [ 69  70  73 141]
 [ 70  65  74 141]
 [ 93  95  91 184]
 [ 79  80  73 152]
 [ 70  73  78 148]
 [ 93  89  96 192]
 [ 78  75  68 147]
 [ 81  90  93 183]
 [ 88  92  86 177]
 [ 78  83  77 159]
 [ 82  86  90 177]
 [ 86  82  89 175]
 [ 78  83  85 175]
 [ 76  83  71 149]
 [ 96  93  95 192]]

[380, 459, 450, 490, 351, 255, 369, 278, 431, 401, 353, 350, 463, 384, 369, 470, 368, 447, 443, 397, 435, 432, 421, 379, 476]


In [99]:
# Q5

file_path = "data-01-test-score.csv"

class ReadCSV():
    def __init__(self, file_path) :
       # TODO
        self.file_path = file_path

    def read_file(self):
        # TODO
        with open(self.file_path, 'r') as f:
          data = list(csv.reader(f))
          for idx in range(len(data)):
            data[idx] = [int(i) for i in data[idx]]
        self.data = data
        return np.array(self.data)

    def merge_list(self):
        # TODO
        return sorted([sum(i)/len(i) for i in self.data])

read_csv = ReadCSV(file_path)
print(read_csv.read_file())
print()
print(read_csv.merge_list())

[[ 73  80  75 152]
 [ 93  88  93 185]
 [ 89  91  90 180]
 [ 96  98 100 196]
 [ 73  66  70 142]
 [ 53  46  55 101]
 [ 69  74  77 149]
 [ 47  56  60 115]
 [ 87  79  90 175]
 [ 79  70  88 164]
 [ 69  70  73 141]
 [ 70  65  74 141]
 [ 93  95  91 184]
 [ 79  80  73 152]
 [ 70  73  78 148]
 [ 93  89  96 192]
 [ 78  75  68 147]
 [ 81  90  93 183]
 [ 88  92  86 177]
 [ 78  83  77 159]
 [ 82  86  90 177]
 [ 86  82  89 175]
 [ 78  83  85 175]
 [ 76  83  71 149]
 [ 96  93  95 192]]

[63.75, 69.5, 87.5, 87.75, 88.25, 92.0, 92.25, 92.25, 94.75, 95.0, 96.0, 99.25, 100.25, 105.25, 107.75, 108.0, 108.75, 110.75, 111.75, 112.5, 114.75, 115.75, 117.5, 119.0, 122.5]
