<a href="https://colab.research.google.com/github/hamzzihyun/coachingstudy-9_AI_basic/blob/main/Week3_mission_jihyun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Q1

arr1 = np.random.rand(5,3)
arr2 = np.random.rand(3,2)

arr_new = arr1 @ arr2
print(arr_new)

[[0.29344026 0.59932717]
 [0.29159789 1.22319219]
 [0.22599828 0.84153633]
 [0.24271881 0.5178981 ]
 [0.77242218 0.98995467]]


In [4]:
# 02

arr1 = np.array([[5,7], [9,11]], float)
arr2 = np.array([[2,4], [6,8]], float)

print("axis = 0 : \n", np.concatenate((arr1, arr2), axis=0))
print("axis = 1 : \n", np.concatenate((arr1, arr2),  axis=1))

axis = 0 : 
 [[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
axis = 1 : 
 [[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


In [10]:
# Q3

xy= np.array([[1., 2., 3., 4., 5., 6.],
            [10.,20.,30.,40.,50.,60.]])

x_train = xy[0]
y_train = xy[1]

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


In [26]:
# Q4
##------------사용 가능한 방법론------------------
"np.random.rand(m,n): 0~1의 균일분포에서 난수 matrix array 생성 \
np.random.randint : 균일분포의 정수 난수 1개 생성 \
np.random.randn: 가우시안 표준 정규 분포에서 난수 matrix array 생성"
##-------------------------------------------------
beta_gd = np.random.randn(1)
bias = np.random.rand(1)

print(beta_gd, bias)

[-0.10636338] [0.53204302]


In [41]:
# Q5

xy= np.array([[1., 2., 3., 4., 5., 6.],
            [3., 6., 9., 12., 15., 18.]])

x_train = xy[0]
y_train = xy[1]

beta_gd = np.random.rand(1)
bias = np.random.rand(1)

learning_rate = 0.01  # 학습률

for i in range(1000):
  pred = (x_train * beta_gd) + bias  # x * 기울기 + 절편
  error = ((pred - y_train) ** 2 ).mean() # 에러(목적식)는 차이의 제곱을 이용해서 계산

  gd_w = ((pred - y_train) * 2 * x_train).mean()  # ((y-y^)^2) w에 대한 편미분
  gd_b = ((pred - y_train) * 2).mean()  # ((y-y^)^2) b에 대한 편미분

  beta_gd -= learning_rate * gd_w  # a -= b는 a = a-b를 의미
  bias -= learning_rate * gd_b


  if i%100 ==0:
        print('Epoch  ({:10d}/1000) error : {:10f}, beta_gd : {:10f}, bias : {:10f}'
        .format(i, error, beta_gd.item(), bias.item()))

Epoch  (         0/1000) error :  84.067644, beta_gd :   1.305081, bias :   0.401492
Epoch  (       100/1000) error :   0.053343, beta_gd :   2.877467, bias :   0.524586
Epoch  (       200/1000) error :   0.025675, beta_gd :   2.914990, bias :   0.363944
Epoch  (       300/1000) error :   0.012358, beta_gd :   2.941023, bias :   0.252494
Epoch  (       400/1000) error :   0.005948, beta_gd :   2.959083, bias :   0.175173
Epoch  (       500/1000) error :   0.002863, beta_gd :   2.971613, bias :   0.121530
Epoch  (       600/1000) error :   0.001378, beta_gd :   2.980306, bias :   0.084314
Epoch  (       700/1000) error :   0.000663, beta_gd :   2.986337, bias :   0.058495
Epoch  (       800/1000) error :   0.000319, beta_gd :   2.990521, bias :   0.040582
Epoch  (       900/1000) error :   0.000154, beta_gd :   2.993424, bias :   0.028155
